import { notFound } from "next/navigation";
import { getPaymentDoc } from "@/lib/repo/operations";
import { getUnitProfile } from "@/lib/repo/masters";
import { amountInWords, fmtDate, inr } from "@/lib/format";
import { PrintToolbar } from "@/components/print/print-toolbar";

export const dynamic = "force-dynamic";

export default async function ReceiptPrintPage({
  params,
}: {
  params: Promise<{ paymentId: string }>;
}) {
  const { paymentId } = await params;
  const id = Number(paymentId);
  const payment = Number.isFinite(id) ? getPaymentDoc(id) : null;
  if (!payment) notFound();

  const unit = getUnitProfile();
  const balance = Math.max(0, payment.invoice_total - payment.paid_amount);
  const receiptNo = `RCP-${String(payment.id).padStart(4, "0")}`;

  return (
    <div className="mx-auto max-w-3xl px-4 py-8 print:max-w-none print:p-0">
      <PrintToolbar backHref="/sales" backLabel="Back to invoices" />
      <article className="mx-auto max-w-3xl rounded-sm bg-white p-8 text-black shadow-2xl print:max-w-none print:rounded-none print:p-0 print:shadow-none">
        <header className="flex flex-wrap items-start justify-between gap-4 border-b-2 border-black pb-4">
          <div>
            <h1 className="display text-2xl leading-none">{unit.name}</h1>
            <p className="mt-1.5 max-w-xs text-[11px] leading-snug text-neutral-600">{unit.address}</p>
            <p className="mt-1 text-[11px] text-neutral-600">
              GSTIN <span className="font-semibold text-black">{unit.gstin}</span>
              {unit.phone ? ` · ${unit.phone}` : null}
            </p>
          </div>
          <div className="text-right">
            <p className="display text-lg tracking-wide">PAYMENT RECEIPT</p>
            <dl className="mt-2 space-y-0.5 text-[11px]">
              <div className="flex justify-end gap-3">
                <dt className="text-neutral-500">Receipt no.</dt>
                <dd className="font-bold">{receiptNo}</dd>
              </div>
              <div className="flex justify-end gap-3">
                <dt className="text-neutral-500">Date</dt>
                <dd className="font-semibold">{fmtDate(payment.date)}</dd>
              </div>
            </dl>
          </div>
        </header>

        <section className="py-5 text-[12px]">
          <p className="text-neutral-600">Received with thanks from</p>
          <p className="mt-1 text-base font-bold">{payment.customer_name ?? "Cash customer"}</p>
          <p className="mt-3 leading-relaxed">
            a sum of <span className="text-sm font-bold">{inr(payment.amount)}</span>{" "}
            <span className="text-neutral-600">({amountInWords(payment.amount)})</span>
          </p>
          <p className="mt-2 text-neutral-700">
            towards payment against Invoice <span className="font-bold text-black">{payment.invoice_no}</span>{" "}
            dated {fmtDate(payment.invoice_date)}.
          </p>
          <p className="mt-1 text-neutral-600">
            Mode <span className="font-semibold text-black uppercase">{payment.mode}</span>
            {payment.reference ? ` · Reference ${payment.reference}` : ""}
            {payment.notes ? ` · ${payment.notes}` : ""}
          </p>
        </section>

        <section className="border-t border-neutral-300 py-4 text-[12px]">
          <Line label="Invoice total" value={inr(payment.invoice_total)} />
          <Line label="Total received to date" value={inr(payment.paid_amount)} />
          <Line label="Balance outstanding" value={inr(balance)} bold highlight={balance > 0.01} />
        </section>

        <footer className="mt-6 flex items-end justify-between gap-6 text-[11px]">
          <p className="max-w-xs text-neutral-500">
            This receipt is computer generated by StoneOps. Please quote {receiptNo} in future
            correspondence.
          </p>
          <div className="text-center">
            <p className="text-neutral-600">For {unit.name}</p>
            <div className="mt-10 w-44 border-t border-black pt-1 text-[10px] tracking-widest uppercase">
              Authorised signatory
            </div>
          </div>
        </footer>
      </article>
    </div>
  );
}

function Line({ label, value, bold, highlight }: { label: string; value: string; bold?: boolean; highlight?: boolean }) {
  return (
    <div className="flex items-center justify-between py-0.5">
      <span className="text-neutral-600">{label}</span>
      <span className={`font${bold ? "-bold" : "-medium"} ${highlight ? "text-red-600" : "text-black"}`}>
        {value}
      </span>
    </div>
  );
}
